INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D010', 'Calidad de Software');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D011', 'Investigación y Desarrollo');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D012', 'Operaciones');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D013', 'Logística');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D014', 'Servicios al Cliente');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D015', 'Comunicaciones');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D016', 'Recursos Humanos');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D017', 'Contabilidad');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D018', 'Legal');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D019', 'Innovación');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D020', 'Desarrollo Web');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D021', 'Desarrollo Móvil');
INSERT INTO employees.departments (dept_no, dept_name) VALUES ('D022', 'Soporte en Línea');
